all_categories = ['analyst',
                 'backenddeveloper',
                 'businessdeveloper',
                 'customerservice',
                 'datascience',
                 'design',
                 'devops',
                 'softwareengineer',
                 'finance',
                 'frontenddeveloper',
                 'fullstackdeveloper',
                 'hr',
                 'legal',
                 'marketing',
                 'mobiledeveloper',
                 'productmanager',
                 'projectmanager',
                 'qa',
                 'sales',
                 'uxui',
                 'other',
                 'entrylevel',
                 'medium',
                 'mediumsenior',
                 'senior',
                 'fulltime',
                 'parttime',
                 'intership',
                 'freelance',
                 'searchfield'
                 ]

job_categories = ['analyst',
                 'backenddeveloper',
                 'businessdeveloper',
                 'customerservice',
                 'datascience',
                 'design',
                 'devops',
                 'softwareengineer',
                 'finance',
                 'frontenddeveloper',
                 'fullstackdeveloper',
                 'hr',
                 'legal',
                 'marketing',
                 'mobiledeveloper',
                 'productmanager',
                 'projectmanager',
                 'qa',
                 'sales',
                 'uxui',
                 'other',
                 ]

job_categories_full = ['Analyst',
                 'Backend Developer',
                 'Business Developer',
                 'Customer Service',
                 'Data Science',
                 'Design',
                 'DevOps',
                 'Software Engineer',
                 'Finance',
                 'Frontend Developer',
                 'Fullstack Developer',
                 'HR',
                 'Legal',
                 'Marketing',
                 'Mobile Developer',
                 'Product Manager',
                 'Project Manager',
                 'QA',
                 'Sales',
                 'UX / UI',
                 'Other'
                 ]

job_categories_promo = [['Customer Service', '/board?category=customerservice'],
                        ['Development', '/board?category=backenddeveloper&category=softwareengineer&category=frontenddeveloper&category=fullstackdeveloper&category=mobiledeveloper'],
                        ['Design', '/board?category=design'],
                        ['HR', '/board?category=hr'],
                        ['Management', '/board?category=productmanager&category=projectmanager'],
                        ['Marketing', '/board?category=marketing'],
                        ['Sales', '/board?category=sales'],
                        ['UX / UI', '/board?category=uxui']
                        ]
job_promo_links = ['/board?category=customerservice',
                   '/board?category=backenddeveloper&category=softwareengineer&category=frontenddeveloper&category=fullstackdeveloper&category=mobiledeveloper',
                   '/board?category=design',
                   '/board?category=hr',
                   '/board?category=productmanager&category=projectmanager',
                   '/board?category=marketing',
                   '/board?category=sales',
                   '/board?category=uxui',]

two_word_categories = ['backend',
                       'business',
                       'customer',
                       'data',
                       'software',
                       'frontend',
                       'fullstack',
                       'mobile',
                       'product',
                       'project',
                       'ux']

test_categories = ['analyst',
                   'developer',
                   'hr',
                   'other']

job_types = ['fulltime',
             'parttime',
             'intership',
             'freelance']


job_types_full = ['Full-time',
             'Part-time',
             'Intership',
             'Freelance']

company_industries_full = ['Advertising',
                      'Agriculture',
                      'Blockchain',
                      'Comsumer Goods',
                      'eCommerce',
                      'Education',
                      'Energy / Greentech',
                      'Entertainment',
                      'Fashion / Living',
                      'Fintech',
                      'Food',
                      'Gaming',
                      'Healthcare',
                      'Hospitality',
                      'IT',
                      'Legal',
                      'Marketing',
                      'Transport',
                      'Recruitment',
                      'Retail',
                      'Robotics',
                      'Saas',
                      'Science',
                      'Service',
                      'Tourism',
                      'Other']

company_industries = ['advertising',
                      'agriculture',
                      'blockchain',
                      'comsumergoods',
                      'ecommerce',
                      'education',
                      'energygreentech',
                      'entertainment',
                      'fashionliving',
                      'fintech',
                      'food',
                      'gaming',
                      'healthcare',
                      'hospitality',
                      'it',
                      'legal',
                      'marketing',
                      'transport',
                      'recruitment',
                      'retail',
                      'robotics',
                      'saas',
                      'science',
                      'service',
                      'tourism',
                      'other']

job_levels = ['entrylevel',
              'medium',
              'mediumsenior',
              'senior']

job_levels_full = ['Entry Level',
          'Medium',
          'Medium-Senior',
          'Senior']

